[workspace]
members = [
    "crates/wire",
    "crates/pbm",
    "crates/cdm",
    "crates/gem",
    "crates/trm",
    "crates/tom",
    "crates/tam",
    "crates/frames",
    "crates/pvgs_client",
    "crates/app",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.76"

[workspace.dependencies]
thiserror = "1"
blake3 = "1"
ucf-protocol = { git = "https://github.com/HUBId/UCF-protocol.git", rev = "57934aaf6ae0c8e63f59decb5dc771309232fddd" }

[profile.release]
opt-level = 3
