[package]
name = "suspension"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ucf-protocol = { workspace = true }

[dev-dependencies]
frames = { path = "../frames" }
