[package]
name = "lnss_sae"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
lnss-candle = []

[dependencies]
lnss_core = { path = "../lnss_core" }
lnss_runtime = { path = "../lnss_runtime" }
