[package]
name = "pvgs_verify"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
ucf-protocol = { workspace = true }
ed25519-dalek = "2"
blake3 = { workspace = true }

[dev-dependencies]
rand = "0.8"
