[package]
name = "pvgs_client"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = { workspace = true }
ucf-protocol = { workspace = true }
pvgs_verify = { path = "../pvgs_verify" }

[dev-dependencies]
ed25519-dalek = "2"
rand = "0.8"
