[package]
name = "cdm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = { workspace = true }
ucf-protocol = { workspace = true }
blake3 = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
