[package]
name = "lnss_hooks"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
lnss-candle = []

[dependencies]
lnss_core = { path = "../lnss_core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
