[package]
name = "lnss_bluebridge"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = []
lnss-pyo3 = []
lnss-cxx = []

[dependencies]
lnss_runtime = { path = "../lnss_runtime" }

[dev-dependencies]
lnss_core = { path = "../lnss_core" }
